// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package database

import (
	"database/sql"
)

type User struct {
	ID             int64
	Name           string
	Email          sql.NullString
	HashedPassword sql.NullString
	Bio            sql.NullString
	AuthToken      string
	CreatedAt      int64
	UpdatedAt      sql.NullInt64
}

type UserSession struct {
	ID           int64
	SessionToken string
	LoginTime    int64
	LogoutTime   sql.NullInt64
	IpAddress    sql.NullString
	UserAgent    sql.NullString
	IsActive     bool
	UserID       int64
}
