// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package database

import (
	"database/sql"
)

type AppState struct {
	ID        int64
	Jwtoption sql.NullString
}

type Mail struct {
	ID      int64
	Subject sql.NullString
	Body    sql.NullString
	Updated sql.NullInt64
}

type User struct {
	ID             int64
	Name           string
	Email          sql.NullString
	HashedPassword sql.NullString
	Bio            sql.NullString
	RefreshToken   string
	AuthToken      string
	CreatedAt      int64
	UpdatedAt      sql.NullInt64
}

type UserSession struct {
	ID           int64
	SessionToken string
	Expires      int64
	LoginTime    int64
	IpAddress    sql.NullString
	UserAgent    sql.NullString
	UserID       int64
}
